name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      ami:
        description: 'AMI ID для EC2 (наприклад, ami-0c55b159cbfafe1f0)'
        type: string
        required: true
        default: 'ami-07e075f00c26b085a'
      instance_type:
        description: 'Тип EC2 інстансу'
        type: choice
        options:
        - t3.micro
        - t3.medium
        - t3.large
        required: true
        default: 't3.micro'
      region:
        description: 'AWS регіон'
        type: choice
        options:
        - eu-north-1
        - eu-west-1
        - ap-south-1
        required: true
        default: 'eu-north-1'
      auto_apply:
        description: 'Автоматично виконати terraform apply?'
        type: boolean
        default: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Directory
      run: ls -la
      working-directory: terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Check if instance exists
      id: check_instance
      run: |
        if terraform state show aws_instance.example >/dev/null 2>&1; then
          echo "instance_exists=true" >> $GITHUB_OUTPUT
          terraform destroy -auto-approve -var="ami=${{ github.event.inputs.ami }}" -var="instance_type=${{ github.event.inputs.instance_type }}" -var="region=${{ github.event.inputs.region }}"
        else
          echo "instance_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Plan
      if: github.event_name == 'workflow_dispatch' && steps.check_instance.outputs.instance_exists == 'false' && github.event.inputs.auto_apply == 'true'
      run: terraform plan -var="ami=${{ github.event.inputs.ami }}" -var="instance_type=${{ github.event.inputs.instance_type }}" -var="region=${{ github.event.inputs.region }}" -out=plan.tfout

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && steps.check_instance.outputs.instance_exists == 'false' && github.event.inputs.auto_apply == 'true'
      run: terraform apply -auto-approve plan.tfout

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch'
      run: terraform destroy -auto-approve -var="ami=${{ github.event.inputs.ami }}" -var="instance_type=${{ github.event.inputs.instance_type }}" -var="region=${{ github.event.inputs.region }}"