name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      ami:
        description: 'AMI ID для EC2'
        type: string
        required: true
        default: 'ami-07e075f00c26b085a'
      instance_type:
        description: 'Тип EC2 інстансу'
        type: choice
        options:
        - t3.micro
        - t3.medium
        - t3.large
        required: true
        default: 't3.micro'
      region:
        description: 'AWS регіон'
        type: choice
        options:
        - eu-north-1
        - eu-west-1
        - ap-south-1
        required: true
        default: 'eu-north-1'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Terraform Init
      run: terraform init

    - name: Check if instance exists
      id: check_instance
      run: |
        if terraform state show aws_instance.example >/dev/null 2>&1; then
          echo "instance_exists=true" >> $GITHUB_OUTPUT
        else
          echo "instance_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Destroy Existing Instance
      if: steps.check_instance.outputs.instance_exists == 'true'
      run: terraform destroy -auto-approve
      env:
        TF_VAR_ami: ${{ github.event.inputs.ami }}
        TF_VAR_instance_type: ${{ github.event.inputs.instance_type }}
        TF_VAR_region: ${{ github.event.inputs.region }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="ami=${{ github.event.inputs.ami }}" -var="instance_type=${{ github.event.inputs.instance_type }}" -var="region=${{ github.event.inputs.region }}"

    - name: Verify Instance Creation
      run: |
        INSTANCE_ID=$(terraform output -raw instance_id)
        aws ec2 describe-instances --instance-ids $INSTANCE_ID --region ${{ github.event.inputs.region }} --query 'Reservations[].Instances[].State.Name' --output text

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_ami: ${{ github.event.inputs.ami }}
        TF_VAR_instance_type: ${{ github.event.inputs.instance_type }}
        TF_VAR_region: ${{ github.event.inputs.region }}
